### ISSUE TITLE
6.31 causing WhatsApp to crash in Android Pie using EdXposed

### ISSUE THREAD

**Issue by bilogic** [suraj0208/WhatsappExtensions#67]
Hi,

```WhatsappExtensions``` partially works, I can see the additional ```Call``` button in the direct message's menu and tapping on it brings up the native phone with number. However, the ```Hide``` button is not there and Whatsapp itself crashes every 1 minute or so. Hope you can help, thank you.

My setup as follows:

Samsung Galaxy A505F, Pie
WhatsApp 2.19.222
Magisk 19.4-736729f5 (19307)
Xposed Framework version 90.0-v0.4.5.1_beta(4463) (YAHFA)

Here is what I extracted from the logs:
```
08-15 08:50:19.101 13504 13504 I EdXposed-Bridge: com.suraj.waext Loaded: com.whatsapp
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.whatsapp.qrcode.WebQrScannerActivity
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:260)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at com.suraj.waext.ExtModule.hookMethodsForLock(ExtModule.java:699)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at com.suraj.waext.ExtModule.handleLoadPackage(ExtModule.java:1650)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:37)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:117)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.impl.HandleBindApp.beforeHookedMethod(HandleBindApp.java:70)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at de.robv.android.xposed.XC_MethodHook.callBeforeHookedMethod(XC_MethodHook.java:51)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at com.elderdrivers.riru.edxp._hooker.yahfa.HandleBindAppHooker.hook(HandleBindAppHooker.java:19)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at android.app.ActivityThread.access$1200(ActivityThread.java:237)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1792)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at android.os.Looper.loop(Looper.java:214)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7076)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: com.whatsapp.qrcode.WebQrScannerActivity
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at java.lang.Class.classForName(Native Method)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at java.lang.Class.forName(Class.java:453)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	... 17 more
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.whatsapp.qrcode.WebQrScannerActivity" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.whatsapp-DhRPCnvW7hGfRNWlGKfy6g==/base.apk"],nativeLibraryDirectories=[/data/app/com.whatsapp-DhRPCnvW7hGfRNWlGKfy6g==/lib/arm64, /data/app/com.whatsapp-DhRPCnvW7hGfRNWlGKfy6g==/base.apk!/lib/arm64-v8a, /system/lib64]]
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-15 08:50:19.994 13504 13504 E EdXposed-Bridge: 	... 21 more
```

**Comment by Makiwha** [comment]
https://github.com/suraj0208/WhatsappExtensions/issues/67#issue-480952155
